"""Settlement reports: printable terminal text, saved files, and PNG charts."""

from __future__ import annotations

from pathlib import Path

from .balances import paid_per_member, total_spent
from .models import Expense, Group, Member, fmt_money
from .settle import Transfer

BAR = "─" * 60


def render_text_report(
    group: Group,
    members: list[Member],
    expenses: list[Expense],
    net: dict[str, int],
    transfers: list[Transfer],
) -> str:
    """Build the full printable settlement report as plain text."""
    lines: list[str] = []
    lines.append(BAR)
    lines.append(f"  SPLITFAIR SETTLEMENT REPORT — {group.name}")
    lines.append(BAR)
    lines.append(f"  Members ({len(members)}): " + ", ".join(m.name for m in members))
    lines.append(f"  Expenses: {len(expenses)}   Total spent: {fmt_money(total_spent(expenses))}")
    lines.append("")

    lines.append("  EXPENSES")
    lines.append(BAR)
    for e in expenses:
        desc = f" — {e.description}" if e.description else ""
        lines.append(
            f"  #{e.id} {e.date}  {e.payer_name} paid {fmt_money(e.amount_cents)}"
            f"  [{e.category}] ({e.split_rule}){desc}"
        )
        for s in e.splits:
            lines.append(f"      · {s.member_name}: owes {fmt_money(s.amount_cents)}")
    if not expenses:
        lines.append("  (no expenses yet)")
    lines.append("")

    lines.append("  NET BALANCES  (+ means owed money, − means owes money)")
    lines.append(BAR)
    paid = paid_per_member(members, expenses)
    for m in members:
        balance = net[m.name]
        if balance > 0:
            status = f"is owed {fmt_money(balance)}"
        elif balance < 0:
            status = f"owes {fmt_money(-balance)}"
        else:
            status = "settled up"
        lines.append(
            f"  {m.name:<12} paid {fmt_money(paid[m.name]):>10}   net {fmt_money(balance):>10}   {status}"
        )
    lines.append("")

    lines.append(f"  SETTLEMENT PLAN — {len(transfers)} transfer(s), fewest possible")
    lines.append(BAR)
    if transfers:
        for i, t in enumerate(transfers, 1):
            lines.append(
                f"  {i}. {t.from_member} → {t.to_member}: {fmt_money(t.amount_cents)}"
            )
    else:
        lines.append("  Everyone is settled up. Nothing to transfer. 🎉")
    lines.append(BAR)
    lines.append("  Generated by SplitFair · min-cash-flow settlement")
    lines.append("")
    return "\n".join(lines)


def save_text_report(text: str, path: str | Path) -> Path:
    out = Path(path).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out


def render_settlement_png(
    group_name: str,
    net: dict[str, int],
    transfers: list[Transfer],
    path: str | Path,
) -> Path:
    """Render a settlement summary chart (balances + transfer plan) to PNG."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    names = sorted(net, key=lambda n: net[n])
    values = [net[n] / 100 for n in names]
    colors = ["#e5484d" if v < 0 else "#30a46c" if v > 0 else "#8b8d98" for v in values]

    fig = plt.figure(figsize=(10, 6), dpi=150)
    fig.patch.set_facecolor("#fafafa")

    ax1 = fig.add_axes([0.10, 0.40, 0.82, 0.50])
    bars = ax1.barh(names, values, color=colors, edgecolor="white", height=0.55)
    ax1.axvline(0, color="#555", linewidth=1)
    ax1.set_title(f"SplitFair — {group_name}: who owes whom", fontsize=14, weight="bold", pad=12)
    span = max(abs(min(values, default=0)), abs(max(values, default=0)), 1)
    pad = 0.025 * span
    for bar, v in zip(bars, values):
        label = f"${v:,.2f}"
        y = bar.get_y() + bar.get_height() / 2
        if abs(v) > 5 * pad:
            # label inside the bar, near its outer end
            x = v - pad if v >= 0 else v + pad
            ax1.text(x, y, label, va="center", ha="right" if v >= 0 else "left",
                     fontsize=10, color="white", weight="bold")
        else:
            # narrow bar: label outside the bar end
            x = v + pad if v >= 0 else v - pad
            ax1.text(x, y, label, va="center", ha="left" if v >= 0 else "right",
                     fontsize=10, color="#333")
    ax1.grid(axis="x", alpha=0.25)
    ax1.set_facecolor("#fafafa")

    ax2 = fig.add_axes([0.10, 0.02, 0.82, 0.30])
    ax2.axis("off")
    if transfers:
        rows = [[f"{i+1}", t.from_member, "→", t.to_member, fmt_money(t.amount_cents)]
                for i, t in enumerate(transfers)]
        table = ax2.table(
            cellText=rows,
            colLabels=["#", "From", "", "To", "Amount"],
            colWidths=[0.08, 0.30, 0.08, 0.30, 0.24],
            loc="center",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        for (r, c), cell in table.get_celld().items():
            cell.set_edgecolor("#ddd")
            if r == 0:
                cell.set_facecolor("#1f1f1f")
                cell.set_text_props(color="white", weight="bold")
            elif r % 2 == 0:
                cell.set_facecolor("#f0f0f0")
        ax2.set_title(f"Settlement plan — {len(transfers)} transfer(s), fewest possible",
                      fontsize=11, weight="bold", pad=8)
    else:
        ax2.text(0.5, 0.5, "Everyone is settled up 🎉", ha="center", va="center", fontsize=13)

    out = Path(path).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    return out
